eight_points_guzzle:
    clients:
        icndb:
            base_url: http://api.icndb.com
            options:
                verify:      false
                timeout:     30
                http_errors: true
                headers:
                    User-Agent: "EightPointsGuzzleBundle/v7"
            plugin: null
